### ISSUE TITLE
Request Support for Non-Standard H Character

### ISSUE THREAD

**Issue by ssell** [Shuttle/Shuttle.Core.Cron#3]
We are using your library to handle cron strings in our .NET Core application. However we have plans in the near future to add support for the **H** non-standard character:

> 'H' is used in the Jenkins continuous integration system to indicate that a "hashed" value is substituted. Thus instead of a fixed number such as '20 * * * *' which means at 20 minutes after the hour every hour, 'H * * * *' indicates that the task is performed every hour at an unspecified but invariant time for each task. This allows spreading out tasks over time, rather than having all of them start at the same time and compete for resources.

https://en.wikipedia.org/wiki/Cron#Non-standard_characters

While we can add special logic on our end to handle this case, it would be nice if support for this character could be added directly into Shuttle.Core.Cron.

**Comment by eben-roux** [comment]
I'm quite happy to implement the `H` option.  However, it appears that external factors determine the actual invariant value.  In this case the result of some form of hashing.

Do you have any expectation in terms of how that value ought to be resolved?  Perhaps some callback of sorts that could be passed into the constructor?

**Comment by ssell** [comment]
A callback is a good idea as it allows for the individual developers to control how the hash is determined. Otherwise it would probably be difficult or finicky trying to decide some factor that works for all cases. 

Especially since this value, at least according to the Jenkins implementation, is invariant and so a simpler solution such as a random time isn't appropriate.

**Comment by eben-roux** [comment]
I have created the following branch:

https://github.com/Shuttle/Shuttle.Core.Cron/tree/SpecifcationFactory

It contains refactored code that would support arbitrary custom expression via a `Specification` provided by an `ISpecificationFactory` implementation.  There is a bit more information in the `README.md`.

Let me know if that works for you and I'll merge it to master and publish it.

**Comment by eben-roux** [comment]
Implemented: https://github.com/Shuttle/Shuttle.Core.Cron/releases/tag/v10.1.0
