### ISSUE TITLE
DayOfWeek # does not work on 7th day of month

### ISSUE THREAD

**Issue by AndrewKorz** [Shuttle/Shuttle.Core.Cron#4]
```
var field = new CronDayOfWeek("6#1");

var date = new DateTime(2011, 01, 01, 0, 0, 0);

Assert.AreEqual(date.AddDays(6), field.GetNext(date));
```

```
Message: Assert.Equal() Failure
Expected: 2011-01-07T00:00:00.0000000
Actual:   2011-02-04T00:00:00.0000000
```

The DayOfWeek # operator does not work with whatever day of week falls on the 7th of the month, in the example it is a Friday where it is unable to find the first Friday of the month, but if instead it looks for "6#2" it would find the expected day of 2011-01-07.
In the example it was Friday, but for another month the issue would happen with whatever day of week is on the 7th day.

**Comment by eben-roux** [comment]
Hi @AndrewKorz ,

Thanks a stack for reporting this.  I have fixed it up (fingers crossed).

- Released: https://www.nuget.org/packages/Shuttle.Core.Cron/10.1.4

Please let me know if this works for you:

```
   private static void Main()
    {
        var cron = new CronExpression("0 0 ? * 6#1", new DateTime(2011, 1, 1));

        for (int i = 0; i < 12; i++)
        {
            Console.WriteLine($"{cron.NextOccurrence()}");
        }
    }
```

```
2011/01/07 00:00:00
2011/02/04 00:00:00
2011/03/04 00:00:00
2011/04/01 00:00:00
2011/05/06 00:00:00
2011/06/03 00:00:00
2011/07/01 00:00:00
2011/08/05 00:00:00
2011/09/02 00:00:00
2011/10/07 00:00:00
2011/11/04 00:00:00
2011/12/02 00:00:00
```

**Comment by AndrewKorz** [comment]
Confirmed fixed.
Thank you for the fast response.
